name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Test FTP Connection and Directory
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_TARGET_DIR: ${{ secrets.FTP_TARGET_DIR }}
        run: |
          lftp -c "
          set ssl:verify-certificate no;
          set ftp:ssl-allow no;
          set ftp:ssl-force no;
          set ftp:ssl-protect-data no;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
          cd $FTP_TARGET_DIR;
          ls;
          bye;
          "
 #deploy by data
      - name: FTP Deploy
        if: success()
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_TARGET_DIR: ${{ secrets.FTP_TARGET_DIR }}
        run: |
          lftp -c "
          set ssl:verify-certificate no;
          set ftp:ssl-allow no;
          set ftp:ssl-force no;
          set ftp:ssl-protect-data no;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
          lcd .;
          cd $FTP_TARGET_DIR;
          mirror --reverse --delete --verbose ./ .;
          bye;